name: "Checkmake"
description: "Install and run checkmake"
inputs:
  go-version:
    description: "Golang version to use"
    default: "1.20"
  working-directory:
    description: "Base directory to use for the action context"
    default: "."

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
      # v5.0.0
      with:
        go-version: ${{ inputs.go-version }}

    - id: find-files
      run: |
        FILES=$(find . \( -name "Makefile" -o -name "makefile" -o -name "GNUmakefile" -o -name "*.mk" -o -name "*.make" \))
        echo "$FILES" >> "$GITHUB_OUTPUT"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - id: scan-files
      env:
        FILES: ${{ steps.find-files.outputs.FILES }}
      run: |
        go install github.com/mrtazz/checkmake/cmd/checkmake@latest
        checkmake $FILES --debug
      shell: bash
      working-directory: ${{ inputs.working-directory }}
