name: Gitleaks

on:
  workflow_call:
    inputs:
      disable-sudo:
        type: boolean
        default: true
      egress-policy-allowlist:
        type: string
        default: ''
      gitleaks-version:
        type: string
        default: 'latest'
      runs-on:
        type: string
        default: 'ubuntu-latest'

jobs:
  gitleaks:
    permissions:
      contents: read
      pull-requests: write
    name: gitleaks
    runs-on: ${{ inputs.runs-on }}
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          disable-sudo-and-containers: ${{ inputs.disable-sudo }}
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            objects.githubusercontent.com:443
            release-assets.githubusercontent.com:443
            ${{ inputs.egress-policy-allowlist }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: gitleaks
        uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e # v3.0.0
        # Comments works only when the workflow is called on `pull_request:`
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
          GITLEAKS_VERSION: ${{ inputs.gitleaks-version }}
