name: Update Clair Vulnerability Database

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * 4" # At 00:00 on Thursday

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf
        # v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349
        # v3.7.1

      - name: Run Clair V4 update
        uses: quay/clair-action@3c05ed02efcfdd9a2aecbd1411754fb1d5927194
        # v0.0.11
        with:
          db-file: matcher.db
          mode: update

      - name: Cache DB
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57
        # v4.2.0
        with:
          path: matcher.db
          key: matcher.db
