name: Infrastructure Security Scan (local repository)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ghas-kics-${{ github.ref }}
  cancel-in-progress: true

jobs:
  infra-scan:
    uses: notdodo/github-actions/.github/workflows/infra-security-scan.yml@2e84638563b65587b42ba8ab87ccdf1922c412dd
    # infra-scan-v0.0.0
