name: Python CI (local repository)
on:
  push:
    branches:
      - main
    paths:
      - auto-tagger/**
  pull_request:
    paths:
      - auto-tagger/**
      - .github/workflows/local-python-ci.yml

concurrency:
  group: ghas-python-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-ci:
    uses: notdodo/github-actions/.github/workflows/python-ci.yml@2e84638563b65587b42ba8ab87ccdf1922c412dd
    # python-ci-v0.0.0
    with:
      poetry-version: 1.8.2
      python-version: 3.11
      working-directory: auto-tagger
