name: Update Clair Vulnerability Database

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 5 * * *" # Everyday at 5AM UTC

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf
        # v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349
        # v3.7.1

      - name: Run Clair V4 update
        uses: quay/clair-action@171b9f2b3391e4bf9e26cabac0e12b7f0705b988
        # v0.0.10
        with:
          db-file: matcher.db
          mode: update

      - name: Cache DB
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a
        # v4.1.2
        with:
          path: matcher.db
          key: matcher.db
