name: Auto Tagger CI (local repository)
on:
  push:
    branches:
      - main
    paths:
      - auto-tagger/**
  pull_request:
    paths:
      - auto-tagger/**
      - .github/workflows/local-python-ci.yml

concurrency:
  group: ghas-auto-tagger-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-ci:
    uses: notdodo/github-actions/.github/workflows/python-ci.yml@python-ci-v0
    with:
      working-directory: auto-tagger

  build-docker-image:
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
      security-events: write
    if: ${{ github.event_name == 'pull_request' }}
    uses: notdodo/github-actions/.github/workflows/docker-build-and-push.yml@docker-build-and-push-v0
    with:
      image: notdodo/auto-tagger
      platforms: linux/amd64
      push: false
      registry: ghcr.io
      working-directory: ./auto-tagger
      egress-policy-allowlist: >
        dl-cdn.alpinelinux.org:443
        pypi.org:443
        files.pythonhosted.org:443
    secrets:
      registry-username: notdodo
      registry-password: ${{ secrets.GITHUB_TOKEN }}
