name: Infrastructure Security Scan (local repository)
on:
  push:
  pull_request:

concurrency:
  group: gha-kics-${{ github.ref }}
  cancel-in-progress: true

jobs:
  kicks:
    runs-on: ubuntu-latest
    steps:
      - name: Run Scan
        uses: notdodo/github-actions/.github/workflows/infra-security-scan.yml@main
